baseURL = ""
languageCode = "en-us"
title = ""
theme = "m10c"

[params]
author = "Rickard Andersson"
avatar = "kittelsen.jpg"
description = " "

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
