baseURL = ""
languageCode = "en-us"
title = ""
theme = "m10c"

[params]
author = "Rickard Andersson"
avatar = "kittelsen.jpg"
description = "I like to write code and learn maths, and sometimes write about it."
